### ISSUE TITLE
Inaccessible contrast on some links

### ISSUE THREAD

**Issue by pglevy** [Bixal/design-token-presentation#3]
They should take the same color as the text to avoid contrast issues like this. If you want to do something other than we have in the template, that's fine, but have to account for accessible contrast.

![image](https://user-images.githubusercontent.com/5177337/139481870-9660cc32-88be-4007-8cf3-ce345905bdc2.png)

**Comment by pglevy** [comment]
also here:

![image](https://user-images.githubusercontent.com/5177337/139482129-1eb97eaf-ea86-41df-8d64-ce7fbd69b06c.png)

**Comment by demi-johnson** [comment]
This is now fixed after editing the config file to match the repo name. But on slide 3 the 'next slide' link is still not appearing 🤔
