### ISSUE TITLE
Let's keep all RRT-related stuff in the Bixal org

### ISSUE THREAD

**Issue by pglevy** [Bixal/design-token-presentation#8]
You should be able to transfer the repo on the Settings page, like this example:

![image](https://user-images.githubusercontent.com/5177337/139482818-c38c0e01-13da-456e-931f-8415d1eea044.png)

**Comment by demi-johnson** [comment]
<img width="1241" alt="Screen Shot 2021-11-04 at 9 34 58 AM" src="https://user-images.githubusercontent.com/87092463/140380676-4e3bd424-a9f6-4f33-8a27-ffcbe7fc2188.png">

**Comment by pglevy** [comment]
I see. Maybe if you give me more access to your repo, I can move this one. I'll have to look further into enabling you all to create repos in Bixal org.

**Comment by pglevy** [comment]
@demi-johnson, following up on this, I think the easiest thing to do would be to transfer to ownership to me (pglevy), and then I can move it to the Bixal account.

**Comment by demi-johnson** [comment]
Okay! Just initiated the transfer.

**Comment by pglevy** [comment]
[Here now](https://github.com/Bixal/design-token-presentation)... thanks!
