### ISSUE TITLE
Consider using text-with-image-link for path to adoption

### ISSUE THREAD

**Issue by pglevy** [Bixal/design-token-presentation#9]
In this case, it seems more appropriate to include the image as content on the page, not as a background. And that way the scaling should work better so it doesn't get cut off. (And you can link out to the reference.)

![image](https://user-images.githubusercontent.com/5177337/139483475-6b688164-3459-40c6-b5cb-2a3902a287af.png)

**Comment by demi-johnson** [comment]
I changed it to the image-with-link template! The image now fits within the slide, but it feels like it's smooshing the text over to the left.
